name: yolo3
channels:
  - defaults
dependencies:
  - python=3.6.10
  - numpy=1.19.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.4
  - pip:
    - opencv-python==4.4.0.42
    - scipy==1.4.1
    - six==1.15.0
    - tensorboard==2.0.2
    - tensorflow-estimator==2.0.1
    - tensorflow-gpu==2.0.0
    - tensornets==0.4.6

